---
- name: enable php8
  command: amazon-linux-extras enable php8.0

- name: install php-fpm
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - "php"
    - "php-cli"
    - "php-mysqlnd"
    - "php-common"
    - "php-fpm"
    - "php-gd"
    - "php-mbstring"
    - "php-xml"
    - "php-dom"
    - "php-intl"
    - "php-simplexml"

- name: Copy config file
  ansible.builtin.copy:
    src: "www.conf"
    dest: /etc/php-fpm.d/
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: permissions for php sessions
  ansible.builtin.file:
    path: /var/lib/php/session
    owner: nginx
    group: nginx
  notify: Restart FPM

- name: fpm as a service
  ansible.builtin.service:
    name: php-fpm
    enabled: yes
...
